### ISSUE TITLE
Maximum call stack size exceeded at RetrieveGlobals._setContextPrototype

### ISSUE THREAD

**Issue by bennypowers** [zachleat/node-retrieve-globals#1]
In an effort to understand how webc works, I'm porting my homepage from njk.

In index.webc, I have this setup script:
```html
<script webc:setup>
  const last5 = [];
  for (const post of [...collections.posts].reverse()) {
    if (last5.length < 5 && (watch || post.data.published)) {
     last5.push(post);
   }
  }
</script>
```
and later on this template:
```html
<ol>
  <li webc:for="post of last5"></li>
</ol>
```
```
[11ty] Problem writing Eleventy templates: (more in DEBUG output)
[11ty] 1. Having trouble rendering webc template ./index.webc (via TemplateContentRenderError)
[11ty] 2. Maximum call stack size exceeded (via RangeError)
[11ty] 
[11ty] Original error stack trace: RangeError: Maximum call stack size exceeded
[11ty]     at RetrieveGlobals._setContextPrototype (/home/bennyp/Developer/bennypowers.dev/node_modules/node-retrieve-globals/retrieveGlobals.cjs:54:22)
[11ty]     at RetrieveGlobals._setContextPrototype (/home/bennyp/Developer/bennypowers.dev/node_modules/node-retrieve-globals/retrieveGlobals.cjs:65:9)
[11ty]     at RetrieveGlobals._setContextPrototype (/home/bennyp/Developer/bennypowers.dev/node_modules/node-retrieve-globals/retrieveGlobals.cjs:65:9)
[11ty]     at RetrieveGlobals._setContextPrototype (/home/bennyp/Developer/bennypowers.dev/node_modules/node-retrieve-globals/retrieveGlobals.cjs:65:9)
[11ty]     at RetrieveGlobals._setContextPrototype (/home/bennyp/Developer/bennypowers.dev/node_modules/node-retrieve-globals/retrieveGlobals.cjs:65:9)
[11ty]     at RetrieveGlobals._setContextPrototype (/home/bennyp/Developer/bennypowers.dev/node_modules/node-retrieve-globals/retrieveGlobals.cjs:65:9)
[11ty]     at RetrieveGlobals._setContextPrototype (/home/bennyp/Developer/bennypowers.dev/node_modules/node-retrieve-globals/retrieveGlobals.cjs:65:9)
[11ty]     at RetrieveGlobals._setContextPrototype (/home/bennyp/Developer/bennypowers.dev/node_modules/node-retrieve-globals/retrieveGlobals.cjs:65:9)
[11ty]     at RetrieveGlobals._setContextPrototype (/home/bennyp/Developer/bennypowers.dev/node_modules/node-retrieve-globals/retrieveGlobals.cjs:65:9)
[11ty]     at RetrieveGlobals._setContextPrototype (/home/bennyp/Developer/bennypowers.dev/node_modules/node-retrieve-globals/retrieveGlobals.cjs:65:9)
```

If I remove the `for .. of` loop from the setup script, I get

```
[11ty] Problem writing Eleventy templates: (more in DEBUG output)
[11ty] 1. Having trouble rendering webc template ./index.webc (via TemplateContentRenderError)
[11ty] 2. loopContent.map is not a function (via TypeError)
[11ty] 
[11ty] Original error stack trace: TypeError: loopContent.map is not a function
[11ty]     at AstSerializer.getLoopContent (file:///home/bennyp/Developer/bennypowers.dev/node_modules/@11ty/webc/src/ast.js:937:27)
[11ty]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[11ty]     at async AstSerializer.compileNode (file:///home/bennyp/Developer/bennypowers.dev/node_modules/@11ty/webc/src/ast.js:960:15)
[11ty]     at async AstSerializer.getChildContent (file:///home/bennyp/Developer/bennypowers.dev/node_modules/@11ty/webc/src/ast.js:347:56)
[11ty]     at async AstSerializer.compileNode (file:///home/bennyp/Developer/bennypowers.dev/node_modules/@11ty/webc/src/ast.js:1170:36)
[11ty]     at async AstSerializer.getChildContent (file:///home/bennyp/Developer/bennypowers.dev/node_modules/@11ty/webc/src/ast.js:347:56)
[11ty]     at async AstSerializer.compileNode (file:///home/bennyp/Developer/bennypowers.dev/node_modules/@11ty/webc/src/ast.js:1170:36)
[11ty]     at async AstSerializer.getChildContent (file:///home/bennyp/Developer/bennypowers.dev/node_modules/@11ty/webc/src/ast.js:347:56)
[11ty]     at async AstSerializer.compileNode (file:///home/bennyp/Developer/bennypowers.dev/node_modules/@11ty/webc/src/ast.js:1170:36)
[11ty]     at async AstSerializer.getChildContent (file:///home/bennyp/Developer/bennypowers.dev/node_modules/@11ty/webc/src/ast.js:347:56)
```

I'm at a loss as to how to proceed. base.webc does not have a setup script

**Comment by zachleat** [comment]
Fixed by https://github.com/zachleat/node-retrieve-globals/commit/4f9b04bbccca349ba3405d39d4690ea4946fcc99

This will ship with `node-retrieve-globals@2.0.8`

**Comment by zachleat** [comment]
2.0.8 has been published.
